name: Run MATLAB Commands on GitHub-Hosted Runner
on: [push]
jobs:
  my-job:
    name: Run MATLAB Commands
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Run commands
        uses: matlab-actions/run-command@v2
        with:
          command: results = runtests, assertSuccess(results);
      - name: Run tests
        uses: matlab-actions/run-tests@v2
      - name: Run build
        uses: matlab-actions/run-build@v2
