name: Run MATLAB Statements
on: [push]
jobs:
  my-job:
    name: Run MATLAB Statements
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Run command
        uses: matlab-actions/run-command@v2
        with:
          command: pwd
          startup-options: -sd subfolder
      - name: Run tests
        uses: matlab-actions/run-tests@v2
        with:
          startup-options: -sd subfolder
      - name: Run build
        uses: matlab-actions/run-build@v2
        with:
          startup-options: -sd subfolder
