name: test parallel computing toolbox

on: [push]

jobs:

  test:

    name: MATLAB ${{ matrix.matlab }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        matlab: [R2022a,R2022b,R2023a,R2023b,R2024a,R2024b]

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.matlab }}

      - name: Test javachk
        uses: matlab-actions/run-command@v2
        with:
          command: javachk('swing')
