name: test parallel computing toolbox

on: [push]

jobs:

  test:

    name: MATLAB ${{ matrix.matlab }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        matlab: [R2021b,R2022a,R2022b]

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB with optimization toolbox and parallel computing toolbox
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.matlab }}
          products: Parallel_Computing_Toolbox

      - name: Test parallel computing
        uses: matlab-actions/run-command@v2
        with:
          command: p = gcp(); p.NumWorkers
