name: test parallel computing toolbox

on: [push]

jobs:

  test:

    name: MATLAB ${{ matrix.matlab }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        matlab: [R2022b]

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Attempt to cURL MPM
        shell: bash
        run: curl -Lv https://www.mathworks.com/mpm/glnxa64/mpm

      # - name: Set up MATLAB with optimization toolbox and parallel computing toolbox
      #   uses: matlab-actions/setup-matlab@v2
      #   with:
      #     release: ${{ matrix.matlab }}
      #     products: Parallel_Computing_Toolbox

      # - name: Test parallel computing
      #   uses: matlab-actions/run-command@v2
      #   with:
      #     command: p = gcp(); p.NumWorkers
